### ISSUE TITLE
As this project been updated to Swift?

### ISSUE THREAD

**Issue by YohannParis** [bdkjones/Kit#19]
Hello, 

I'm looking into using the project on my own, and I wondered if it has been converted to Swift?

Thanks

**Comment by bdkjones** [comment]
No. The Kit compiler has not been rewritten in Swift because there's no reason to do so. Swift's String type is really cumbersome compared to NSString and most of the compiler is pointer-arithmetic in C. Using C pointers in Swift is also a godawful experience.

I'd recommend a Swift wrapper around the current ObjC methods.
